---
# handlers for ansible-role-docker-mysql_exporter
# /home/baldev/ansible/roles/ansible-role-docker-mysql-node-exporter-master/handlers/main.yml

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: restart mysql_exporter
  service:
    name: mysql_exporter
    state: restarted
    enabled: true

- name: start mysql_exporter
  service:
    name: mysql_exporter
    state: started
    enabled: true

- name: reload mysql_exporter
  service:
    name: mysql_exporter
    state: reloaded
    enabled: true
